#version 460

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(set = 0, binding = 0) uniform sampler2D u_EquirectMap;
layout(set = 0, binding = 1, rgba16f) writeonly uniform imageCube u_CubeMap;

const vec2 invAtan = vec2(0.1591, 0.3183);

vec2 SampleSphericalMap(vec3 v)
{
    vec2 uv = vec2(atan(v.z, v.x), asin(v.y));
    uv *= invAtan;
    uv += 0.5;
    return uv;
}

vec3 getCubeDirection(uint face, vec2 uv) {
    vec2 st = uv * 2.0 - 1.0;
    switch(face) {
        case 0: return vec3( 1.0, -st.y, -st.x); // +X
        case 1: return vec3(-1.0, -st.y,  st.x); // -X
        case 2: return vec3( st.x,  1.0,  st.y); // +Y
        case 3: return vec3( st.x, -1.0, -st.y); // -Y
        case 4: return vec3( st.x, -st.y,  1.0); // +Z
        case 5: return vec3(-st.x, -st.y, -1.0); // -Z
    }
    return vec3(0);
}

void main() {
    uint face = gl_GlobalInvocationID.z;
    ivec2 size = imageSize(u_CubeMap);

    if (gl_GlobalInvocationID.x >= size.x || gl_GlobalInvocationID.y >= size.y || face >= 6)
        return;

    vec2 uv = (vec2(gl_GlobalInvocationID.xy) + 0.5) / vec2(size);
    vec3 dir = normalize(getCubeDirection(face, uv));
    vec2 equirectUV = SampleSphericalMap(dir);
    vec4 color = texture(u_EquirectMap, equirectUV);
    imageStore(u_CubeMap, ivec3(gl_GlobalInvocationID.xy, face), color);
}
