#version 460

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(set = 0, binding = 0) uniform samplerCube u_EnvironmentMap;
layout(set = 0, binding = 1, rgba16f) writeonly uniform imageCube u_IrradianceMap;

const float PI = 3.14159265359;

vec3 getCubeDirection(uint face, vec2 uv) {
    vec2 st = uv * 2.0 - 1.0;
    switch(face) {
        case 0: return vec3( 1.0, -st.y, -st.x); // +X
        case 1: return vec3(-1.0, -st.y,  st.x); // -X
        case 2: return vec3( st.x,  1.0,  st.y); // +Y
        case 3: return vec3( st.x, -1.0, -st.y); // -Y
        case 4: return vec3( st.x, -st.y,  1.0); // +Z
        case 5: return vec3(-st.x, -st.y, -1.0); // -Z
    }
    return vec3(0);
}

void main() {
    uint face = gl_GlobalInvocationID.z;
    ivec2 size = imageSize(u_IrradianceMap);

    if (gl_GlobalInvocationID.x >= size.x || gl_GlobalInvocationID.y >= size.y || face >= 6)
        return;

    vec2 uv = (vec2(gl_GlobalInvocationID.xy) + 0.5) / vec2(size);
    vec3 N = normalize(getCubeDirection(face, uv));

    vec3 irradiance = vec3(0.0);

    // tangent space calculation from origin point
    vec3 up    = vec3(0.0, 1.0, 0.0);
    vec3 right = normalize(cross(up, N));
    up         = normalize(cross(N, right));

    float sampleDelta = 0.025;
    float nrSamples = 0.0;
    for(float phi = 0.0; phi < 2.0 * PI; phi += sampleDelta)
    {
        for(float theta = 0.0; theta < 0.5 * PI; theta += sampleDelta)
        {
            // spherical to cartesian (in tangent space)
            vec3 tangentSample = vec3(sin(theta) * cos(phi), sin(theta) * sin(phi), cos(theta));
            // tangent space to world
            vec3 sampleVec = tangentSample.x * right + tangentSample.y * up + tangentSample.z * N;

            irradiance += texture(u_EnvironmentMap, sampleVec).rgb * cos(theta) * sin(theta);
            nrSamples++;
        }
    }
    irradiance = PI * irradiance * (1.0 / float(nrSamples));

    imageStore(u_IrradianceMap, ivec3(gl_GlobalInvocationID.xy, face), vec4(irradiance, 1.0));
}
