#pragma once
#include <cstdint>

namespace helios {

// Values match GLFW key codes exactly so conversion is static_cast<int>(KeyCode).
enum class KeyCode : int32_t {
    Unknown        = -1,

    // Printable keys
    Space          = 32,
    Apostrophe     = 39,
    Comma          = 44,
    Minus          = 45,
    Period         = 46,
    Slash          = 47,
    Num0           = 48,
    Num1           = 49,
    Num2           = 50,
    Num3           = 51,
    Num4           = 52,
    Num5           = 53,
    Num6           = 54,
    Num7           = 55,
    Num8           = 56,
    Num9           = 57,
    Semicolon      = 59,
    Equal          = 61,
    A              = 65,
    B              = 66,
    C              = 67,
    D              = 68,
    E              = 69,
    F              = 70,
    G              = 71,
    H              = 72,
    I              = 73,
    J              = 74,
    K              = 75,
    L              = 76,
    M              = 77,
    N              = 78,
    O              = 79,
    P              = 80,
    Q              = 81,
    R              = 82,
    S              = 83,
    T              = 84,
    U              = 85,
    V              = 86,
    W              = 87,
    X              = 88,
    Y              = 89,
    Z              = 90,
    LeftBracket    = 91,
    Backslash      = 92,
    RightBracket   = 93,
    GraveAccent    = 96,

    // Function keys
    Escape         = 256,
    Enter          = 257,
    Tab            = 258,
    Backspace      = 259,
    Insert         = 260,
    Delete         = 261,
    Right          = 262,
    Left           = 263,
    Down           = 264,
    Up             = 265,
    PageUp         = 266,
    PageDown       = 267,
    Home           = 268,
    End            = 269,
    CapsLock       = 280,
    ScrollLock     = 281,
    NumLock        = 282,
    PrintScreen    = 283,
    Pause          = 284,
    F1             = 290,
    F2             = 291,
    F3             = 292,
    F4             = 293,
    F5             = 294,
    F6             = 295,
    F7             = 296,
    F8             = 297,
    F9             = 298,
    F10            = 299,
    F11            = 300,
    F12            = 301,
    KP0            = 320,
    KP1            = 321,
    KP2            = 322,
    KP3            = 323,
    KP4            = 324,
    KP5            = 325,
    KP6            = 326,
    KP7            = 327,
    KP8            = 328,
    KP9            = 329,
    KPDecimal      = 330,
    KPDivide       = 331,
    KPMultiply     = 332,
    KPSubtract     = 333,
    KPAdd          = 334,
    KPEnter        = 335,
    KPEqual        = 336,
    LeftShift      = 340,
    LeftControl    = 341,
    LeftAlt        = 342,
    LeftSuper      = 343,
    RightShift     = 344,
    RightControl   = 345,
    RightAlt       = 346,
    RightSuper     = 347,
    Menu           = 348,

    // Sentinel for array sizing. GLFW_KEY_LAST is 348.
    _Count         = 349,
};

enum class MouseButton : int32_t {
    Left    = 0,
    Right   = 1,
    Middle  = 2,
    Button4 = 3,
    Button5 = 4,
    Button6 = 5,
    Button7 = 6,
    Button8 = 7,

    _Count  = 8,
};

// Placeholders for future gamepad support.
enum class GamepadButton : int32_t {
    A = 0, B = 1, X = 2, Y = 3,
    LeftBumper = 4, RightBumper = 5,
    Back = 6, Start = 7, Guide = 8,
    LeftThumb = 9, RightThumb = 10,
    DPadUp = 11, DPadRight = 12, DPadDown = 13, DPadLeft = 14,
    _Count = 15,
};

enum class GamepadAxis : int32_t {
    None         = -1,
    LeftX        = 0,
    LeftY        = 1,
    RightX       = 2,
    RightY       = 3,
    LeftTrigger  = 4,
    RightTrigger = 5,
    _Count       = 6,
};

} // namespace helios
